// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Mictlanix.CFDv32 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/leyendasFiscales")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/leyendasFiscales", IsNullable=false)]
    public partial class LeyendasFiscales {
        
        private string versionField;
        
        private LeyendasFiscalesLeyenda[] leyendaField;
		
		public LeyendasFiscales() {
			this.versionField = "1.0";
		}

        /// <remarks>
		///Atributo requerido para expresar la versión del complemento de Leyendas Fiscales
		///</remarks>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks>
		///Nodo para expresar la(s) leyenda(s) fiscal(es) que apliquen al comprobante
		///</remarks>
        [System.Xml.Serialization.XmlElementAttribute("Leyenda")]
        public LeyendasFiscalesLeyenda[] Leyenda {
            get {
                return this.leyendaField;
            }
            set {
                this.leyendaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/leyendasFiscales")]
    public partial class LeyendasFiscalesLeyenda {
        
        private string disposicionFiscalField;
        
        private string normaField;
        
        private string textoLeyendaField;
        
        /// <remarks>
///Atributo opcional para especificar la Ley, Resolución o Disposición fiscal que regula la leyenda, deberá expresarse en siglas de mayúsculas y sin puntuación (p. ej: ISR)
///</remarks>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string disposicionFiscal {
            get {
                return this.disposicionFiscalField;
            }
            set {
                this.disposicionFiscalField = value;
            }
        }
        
        /// <remarks>
///Atributo opcional para especificar el número de Artículo o en su caso Regla que regula la obligación de la leyenda
///</remarks>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string norma {
            get {
                return this.normaField;
            }
            set {
                this.normaField = value;
            }
        }
        
        /// <remarks>
///Atributo requerido para especificar la leyenda fiscal
///</remarks>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string textoLeyenda {
            get {
                return this.textoLeyendaField;
            }
            set {
                this.textoLeyendaField = value;
            }
        }
    }
}
