//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8789
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace Mictlanix.CFDv33 {
	using System.Xml.Serialization;


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute (Namespace = "", IsNullable = false)]
	public partial class Acuse {

		private Folios foliosField;

		private Signature signatureField;

		private System.DateTime fechaField;

		private string rfcEmisorField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute (Namespace = "http://cancelacfd.sat.gob.mx")]
		public Folios Folios {
			get {
				return this.foliosField;
			}
			set {
				this.foliosField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute (Namespace = "http://www.w3.org/2000/09/xmldsig#")]
		public Signature Signature {
			get {
				return this.signatureField;
			}
			set {
				this.signatureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public System.DateTime Fecha {
			get {
				return this.fechaField;
			}
			set {
				this.fechaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string RfcEmisor {
			get {
				return this.rfcEmisorField;
			}
			set {
				this.rfcEmisorField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://cancelacfd.sat.gob.mx")]
	[System.Xml.Serialization.XmlRootAttribute (Namespace = "http://cancelacfd.sat.gob.mx", IsNullable = false)]
	public partial class Folios {

		private string uUIDField;

		private string estatusUUIDField;

		/// <remarks/>
		public string UUID {
			get {
				return this.uUIDField;
			}
			set {
				this.uUIDField = value;
			}
		}

		/// <remarks/>
		public string EstatusUUID {
			get {
				return this.estatusUUIDField;
			}
			set {
				this.estatusUUIDField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
	[System.Xml.Serialization.XmlRootAttribute (Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
	public partial class Signature {

		private string signatureValueField;

		private SignatureSignedInfo signedInfoField;

		private SignatureKeyInfo keyInfoField;

		private string idField;

		/// <remarks/>
		//[System.Xml.Serialization.XmlElementAttribute ("SignedInfo")]
		public SignatureSignedInfo SignedInfo {
			get {
				return this.signedInfoField;
			}
			set {
				this.signedInfoField = value;
			}
		}

		/// <remarks/>
		public string SignatureValue {
			get {
				return this.signatureValueField;
			}
			set {
				this.signatureValueField = value;
			}
		}

		/// <remarks/>
		public SignatureKeyInfo KeyInfo {
			get {
				return this.keyInfoField;
			}
			set {
				this.keyInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
	public partial class SignatureSignedInfo {

		private SignatureSignedInfoCanonicalizationMethod canonicalizationMethodField;

		private SignatureSignedInfoSignatureMethod signatureMethodField;

		private SignatureSignedInfoReference referenceField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute ("CanonicalizationMethod")]
		public SignatureSignedInfoCanonicalizationMethod CanonicalizationMethod {
			get {
				return this.canonicalizationMethodField;
			}
			set {
				this.canonicalizationMethodField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute ("SignatureMethod")]
		public SignatureSignedInfoSignatureMethod SignatureMethod {
			get {
				return this.signatureMethodField;
			}
			set {
				this.signatureMethodField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute ("Reference")]
		public SignatureSignedInfoReference Reference {
			get {
				return this.referenceField;
			}
			set {
				this.referenceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
	public partial class SignatureSignedInfoCanonicalizationMethod {

		private string algorithmField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Algorithm {
			get {
				return this.algorithmField;
			}
			set {
				this.algorithmField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
	public partial class SignatureSignedInfoSignatureMethod {

		private string algorithmField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Algorithm {
			get {
				return this.algorithmField;
			}
			set {
				this.algorithmField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
	public partial class SignatureSignedInfoReference {

		private string digestValueField;

		private SignatureSignedInfoReferenceTransformsTransform [] transformsField;

		private SignatureSignedInfoReferenceDigestMethod digestMethodField;

		private string uRIField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute ("Transform", typeof (SignatureSignedInfoReferenceTransformsTransform), IsNullable = false)]
		public SignatureSignedInfoReferenceTransformsTransform [] Transforms {
			get {
				return this.transformsField;
			}
			set {
				this.transformsField = value;
			}
		}

		/// <remarks/>
		public SignatureSignedInfoReferenceDigestMethod DigestMethod {
			get {
				return this.digestMethodField;
			}
			set {
				this.digestMethodField = value;
			}
		}

		/// <remarks/>
		public string DigestValue {
			get {
				return this.digestValueField;
			}
			set {
				this.digestValueField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string URI {
			get {
				return this.uRIField;
			}
			set {
				this.uRIField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
	public partial class SignatureSignedInfoReferenceTransformsTransform {

		private string xPathField;

		private string algorithmField;

		/// <remarks/>
		public string XPath {
			get {
				return this.xPathField;
			}
			set {
				this.xPathField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Algorithm {
			get {
				return this.algorithmField;
			}
			set {
				this.algorithmField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
	public partial class SignatureSignedInfoReferenceDigestMethod {

		private string algorithmField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Algorithm {
			get {
				return this.algorithmField;
			}
			set {
				this.algorithmField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
	public partial class SignatureKeyInfo {

		private string keyNameField;

		private SignatureKeyInfoKeyValueRSAKeyValue [] keyValueField;

		/// <remarks/>
		public string KeyName {
			get {
				return this.keyNameField;
			}
			set {
				this.keyNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute ("RSAKeyValue", typeof (SignatureKeyInfoKeyValueRSAKeyValue), IsNullable = false)]
		public SignatureKeyInfoKeyValueRSAKeyValue [] KeyValue {
			get {
				return this.keyValueField;
			}
			set {
				this.keyValueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
	public partial class SignatureKeyInfoKeyValueRSAKeyValue {

		private string modulusField;

		private string exponentField;

		/// <remarks/>
		public string Modulus {
			get {
				return this.modulusField;
			}
			set {
				this.modulusField = value;
			}
		}

		/// <remarks/>
		public string Exponent {
			get {
				return this.exponentField;
			}
			set {
				this.exponentField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute (Namespace = "", IsNullable = false)]
	public partial class NewDataSet {

		private Acuse [] itemsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute ("Acuse")]
		public Acuse [] Items {
			get {
				return this.itemsField;
			}
			set {
				this.itemsField = value;
			}
		}
	}
}