//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Mictlanix.CFDv33 {
    using System.Xml.Serialization;
    
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "4.6.1055.0")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/ComercioExterior11")]
	[System.Xml.Serialization.XmlRootAttribute (Namespace = "http://www.sat.gob.mx/ComercioExterior11", IsNullable = false)]
	public partial class ComercioExterior {

		private ComercioExteriorEmisor emisorField;

		private ComercioExteriorPropietario [] propietarioField;

		private ComercioExteriorReceptor receptorField;

		private ComercioExteriorDestinatario [] destinatarioField;

		private ComercioExteriorMercancia [] mercanciasField;

		private string versionField;

		private c_MotivoTraslado motivoTrasladoField;

		private bool motivoTrasladoFieldSpecified;

		private c_TipoOperacion tipoOperacionField;

		private c_ClavePedimento claveDePedimentoField;

		private bool claveDePedimentoFieldSpecified;

		private int certificadoOrigenField;

		private bool certificadoOrigenFieldSpecified;

		private string numCertificadoOrigenField;

		private string numeroExportadorConfiableField;

		private c_INCOTERM incotermField;

		private bool incotermFieldSpecified;

		private int subdivisionField;

		private bool subdivisionFieldSpecified;

		private string observacionesField;

		private decimal tipoCambioUSDField;

		private bool tipoCambioUSDFieldSpecified;

		private decimal totalUSDField;

		private bool totalUSDFieldSpecified;

		public ComercioExterior ()
		{
			this.versionField = "1.1";
		}

		/// <remarks/>
		public ComercioExteriorEmisor Emisor {
			get {
				return this.emisorField;
			}
			set {
				this.emisorField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute ("Propietario")]
		public ComercioExteriorPropietario [] Propietario {
			get {
				return this.propietarioField;
			}
			set {
				this.propietarioField = value;
			}
		}

		/// <remarks/>
		public ComercioExteriorReceptor Receptor {
			get {
				return this.receptorField;
			}
			set {
				this.receptorField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute ("Destinatario")]
		public ComercioExteriorDestinatario [] Destinatario {
			get {
				return this.destinatarioField;
			}
			set {
				this.destinatarioField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute ("Mercancia", IsNullable = false)]
		public ComercioExteriorMercancia [] Mercancias {
			get {
				return this.mercanciasField;
			}
			set {
				this.mercanciasField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Version {
			get {
				return this.versionField;
			}
			set {
				this.versionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public c_MotivoTraslado MotivoTraslado {
			get {
				return this.motivoTrasladoField;
			}
			set {
				this.motivoTrasladoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool MotivoTrasladoSpecified {
			get {
				return this.motivoTrasladoFieldSpecified;
			}
			set {
				this.motivoTrasladoFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public c_TipoOperacion TipoOperacion {
			get {
				return this.tipoOperacionField;
			}
			set {
				this.tipoOperacionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public c_ClavePedimento ClaveDePedimento {
			get {
				return this.claveDePedimentoField;
			}
			set {
				this.claveDePedimentoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool ClaveDePedimentoSpecified {
			get {
				return this.claveDePedimentoFieldSpecified;
			}
			set {
				this.claveDePedimentoFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public int CertificadoOrigen {
			get {
				return this.certificadoOrigenField;
			}
			set {
				this.certificadoOrigenField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool CertificadoOrigenSpecified {
			get {
				return this.certificadoOrigenFieldSpecified;
			}
			set {
				this.certificadoOrigenFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NumCertificadoOrigen {
			get {
				return this.numCertificadoOrigenField;
			}
			set {
				this.numCertificadoOrigenField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NumeroExportadorConfiable {
			get {
				return this.numeroExportadorConfiableField;
			}
			set {
				this.numeroExportadorConfiableField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public c_INCOTERM Incoterm {
			get {
				return this.incotermField;
			}
			set {
				this.incotermField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool IncotermSpecified {
			get {
				return this.incotermFieldSpecified;
			}
			set {
				this.incotermFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public int Subdivision {
			get {
				return this.subdivisionField;
			}
			set {
				this.subdivisionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool SubdivisionSpecified {
			get {
				return this.subdivisionFieldSpecified;
			}
			set {
				this.subdivisionFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Observaciones {
			get {
				return this.observacionesField;
			}
			set {
				this.observacionesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal TipoCambioUSD {
			get {
				return this.tipoCambioUSDField;
			}
			set {
				this.tipoCambioUSDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool TipoCambioUSDSpecified {
			get {
				return this.tipoCambioUSDFieldSpecified;
			}
			set {
				this.tipoCambioUSDFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal TotalUSD {
			get {
				return this.totalUSDField;
			}
			set {
				this.totalUSDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool TotalUSDSpecified {
			get {
				return this.totalUSDFieldSpecified;
			}
			set {
				this.totalUSDFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "4.6.1055.0")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/ComercioExterior11")]
	public partial class ComercioExteriorEmisor {

		private ComercioExteriorEmisorDomicilio domicilioField;

		private string curpField;

		/// <remarks/>
		public ComercioExteriorEmisorDomicilio Domicilio {
			get {
				return this.domicilioField;
			}
			set {
				this.domicilioField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Curp {
			get {
				return this.curpField;
			}
			set {
				this.curpField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "4.6.1055.0")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/ComercioExterior11")]
	public partial class ComercioExteriorEmisorDomicilio {

		private string calleField;

		private string numeroExteriorField;

		private string numeroInteriorField;

		private string coloniaField;

		private bool coloniaFieldSpecified;

		private string localidadField;

		private bool localidadFieldSpecified;

		private string referenciaField;

		private string municipioField;

		private bool municipioFieldSpecified;

		private c_Estado estadoField;

		private string paisField;

		private string codigoPostalField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Calle {
			get {
				return this.calleField;
			}
			set {
				this.calleField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NumeroExterior {
			get {
				return this.numeroExteriorField;
			}
			set {
				this.numeroExteriorField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NumeroInterior {
			get {
				return this.numeroInteriorField;
			}
			set {
				this.numeroInteriorField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Colonia {
			get {
				return this.coloniaField;
			}
			set {
				this.coloniaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool ColoniaSpecified {
			get {
				return this.coloniaFieldSpecified;
			}
			set {
				this.coloniaFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Localidad {
			get {
				return this.localidadField;
			}
			set {
				this.localidadField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool LocalidadSpecified {
			get {
				return this.localidadFieldSpecified;
			}
			set {
				this.localidadFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Referencia {
			get {
				return this.referenciaField;
			}
			set {
				this.referenciaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Municipio {
			get {
				return this.municipioField;
			}
			set {
				this.municipioField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool MunicipioSpecified {
			get {
				return this.municipioFieldSpecified;
			}
			set {
				this.municipioFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public c_Estado Estado {
			get {
				return this.estadoField;
			}
			set {
				this.estadoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Pais {
			get {
				return this.paisField;
			}
			set {
				this.paisField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string CodigoPostal {
			get {
				return this.codigoPostalField;
			}
			set {
				this.codigoPostalField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "4.6.1055.0")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/ComercioExterior11")]
	public partial class ComercioExteriorPropietario {

		private string numRegIdTribField;

		private string residenciaFiscalField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NumRegIdTrib {
			get {
				return this.numRegIdTribField;
			}
			set {
				this.numRegIdTribField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string ResidenciaFiscal {
			get {
				return this.residenciaFiscalField;
			}
			set {
				this.residenciaFiscalField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "4.6.1055.0")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/ComercioExterior11")]
	public partial class ComercioExteriorReceptor {

		private ComercioExteriorReceptorDomicilio domicilioField;

		private string numRegIdTribField;

		/// <remarks/>
		public ComercioExteriorReceptorDomicilio Domicilio {
			get {
				return this.domicilioField;
			}
			set {
				this.domicilioField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NumRegIdTrib {
			get {
				return this.numRegIdTribField;
			}
			set {
				this.numRegIdTribField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "4.6.1055.0")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/ComercioExterior11")]
	public partial class ComercioExteriorReceptorDomicilio {

		private string calleField;

		private string numeroExteriorField;

		private string numeroInteriorField;

		private string coloniaField;

		private string localidadField;

		private string referenciaField;

		private string municipioField;

		private string estadoField;

		private string paisField;

		private string codigoPostalField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Calle {
			get {
				return this.calleField;
			}
			set {
				this.calleField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NumeroExterior {
			get {
				return this.numeroExteriorField;
			}
			set {
				this.numeroExteriorField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NumeroInterior {
			get {
				return this.numeroInteriorField;
			}
			set {
				this.numeroInteriorField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Colonia {
			get {
				return this.coloniaField;
			}
			set {
				this.coloniaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Localidad {
			get {
				return this.localidadField;
			}
			set {
				this.localidadField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Referencia {
			get {
				return this.referenciaField;
			}
			set {
				this.referenciaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Municipio {
			get {
				return this.municipioField;
			}
			set {
				this.municipioField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Estado {
			get {
				return this.estadoField;
			}
			set {
				this.estadoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Pais {
			get {
				return this.paisField;
			}
			set {
				this.paisField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string CodigoPostal {
			get {
				return this.codigoPostalField;
			}
			set {
				this.codigoPostalField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "4.6.1055.0")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/ComercioExterior11")]
	public partial class ComercioExteriorDestinatario {

		private ComercioExteriorDestinatarioDomicilio [] domicilioField;

		private string numRegIdTribField;

		private string nombreField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute ("Domicilio")]
		public ComercioExteriorDestinatarioDomicilio [] Domicilio {
			get {
				return this.domicilioField;
			}
			set {
				this.domicilioField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NumRegIdTrib {
			get {
				return this.numRegIdTribField;
			}
			set {
				this.numRegIdTribField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Nombre {
			get {
				return this.nombreField;
			}
			set {
				this.nombreField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "4.6.1055.0")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/ComercioExterior11")]
	public partial class ComercioExteriorDestinatarioDomicilio {

		private string calleField;

		private string numeroExteriorField;

		private string numeroInteriorField;

		private string coloniaField;

		private string localidadField;

		private string referenciaField;

		private string municipioField;

		private string estadoField;

		private string paisField;

		private string codigoPostalField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Calle {
			get {
				return this.calleField;
			}
			set {
				this.calleField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NumeroExterior {
			get {
				return this.numeroExteriorField;
			}
			set {
				this.numeroExteriorField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NumeroInterior {
			get {
				return this.numeroInteriorField;
			}
			set {
				this.numeroInteriorField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Colonia {
			get {
				return this.coloniaField;
			}
			set {
				this.coloniaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Localidad {
			get {
				return this.localidadField;
			}
			set {
				this.localidadField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Referencia {
			get {
				return this.referenciaField;
			}
			set {
				this.referenciaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Municipio {
			get {
				return this.municipioField;
			}
			set {
				this.municipioField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Estado {
			get {
				return this.estadoField;
			}
			set {
				this.estadoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Pais {
			get {
				return this.paisField;
			}
			set {
				this.paisField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string CodigoPostal {
			get {
				return this.codigoPostalField;
			}
			set {
				this.codigoPostalField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "4.6.1055.0")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/ComercioExterior11")]
	public partial class ComercioExteriorMercancia {

		private ComercioExteriorMercanciaDescripcionesEspecificas [] descripcionesEspecificasField;

		private string noIdentificacionField;

		private string fraccionArancelariaField;

		private bool fraccionArancelariaFieldSpecified;

		private decimal cantidadAduanaField;

		private bool cantidadAduanaFieldSpecified;

		private c_UnidadAduana unidadAduanaField;

		private bool unidadAduanaFieldSpecified;

		private decimal valorUnitarioAduanaField;

		private bool valorUnitarioAduanaFieldSpecified;

		private decimal valorDolaresField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute ("DescripcionesEspecificas")]
		public ComercioExteriorMercanciaDescripcionesEspecificas [] DescripcionesEspecificas {
			get {
				return this.descripcionesEspecificasField;
			}
			set {
				this.descripcionesEspecificasField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NoIdentificacion {
			get {
				return this.noIdentificacionField;
			}
			set {
				this.noIdentificacionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string FraccionArancelaria {
			get {
				return this.fraccionArancelariaField;
			}
			set {
				this.fraccionArancelariaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool FraccionArancelariaSpecified {
			get {
				return this.fraccionArancelariaFieldSpecified;
			}
			set {
				this.fraccionArancelariaFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal CantidadAduana {
			get {
				return this.cantidadAduanaField;
			}
			set {
				this.cantidadAduanaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool CantidadAduanaSpecified {
			get {
				return this.cantidadAduanaFieldSpecified;
			}
			set {
				this.cantidadAduanaFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public c_UnidadAduana UnidadAduana {
			get {
				return this.unidadAduanaField;
			}
			set {
				this.unidadAduanaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool UnidadAduanaSpecified {
			get {
				return this.unidadAduanaFieldSpecified;
			}
			set {
				this.unidadAduanaFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal ValorUnitarioAduana {
			get {
				return this.valorUnitarioAduanaField;
			}
			set {
				this.valorUnitarioAduanaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool ValorUnitarioAduanaSpecified {
			get {
				return this.valorUnitarioAduanaFieldSpecified;
			}
			set {
				this.valorUnitarioAduanaFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal ValorDolares {
			get {
				return this.valorDolaresField;
			}
			set {
				this.valorDolaresField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "4.6.1055.0")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/ComercioExterior11")]
	public partial class ComercioExteriorMercanciaDescripcionesEspecificas {

		private string marcaField;

		private string modeloField;

		private string subModeloField;

		private string numeroSerieField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Marca {
			get {
				return this.marcaField;
			}
			set {
				this.marcaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Modelo {
			get {
				return this.modeloField;
			}
			set {
				this.modeloField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string SubModelo {
			get {
				return this.subModeloField;
			}
			set {
				this.subModeloField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NumeroSerie {
			get {
				return this.numeroSerieField;
			}
			set {
				this.numeroSerieField = value;
			}
		}
	}
}
