//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace Mictlanix.CFDv33 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/nomina12", IsNullable=false)]
    public partial class Nomina {
        
        private NominaEmisor emisorField;
        
        private NominaReceptor receptorField;
        
        private NominaPercepciones percepcionesField;
        
        private NominaDeducciones deduccionesField;
        
        private NominaOtroPago[] otrosPagosField;
        
        private NominaIncapacidad[] incapacidadesField;
        
        private string versionField;
        
        private c_TipoNomina tipoNominaField;
        
        private System.DateTime fechaPagoField;
        
        private System.DateTime fechaInicialPagoField;
        
        private System.DateTime fechaFinalPagoField;
        
        private decimal numDiasPagadosField;
        
        private decimal totalPercepcionesField;
        
        private bool totalPercepcionesFieldSpecified;
        
        private decimal totalDeduccionesField;
        
        private bool totalDeduccionesFieldSpecified;
        
        private decimal totalOtrosPagosField;
        
        private bool totalOtrosPagosFieldSpecified;
        
        public Nomina() {
            this.versionField = "1.2";
        }
        
        /// <remarks/>
        public NominaEmisor Emisor {
            get {
                return this.emisorField;
            }
            set {
                this.emisorField = value;
            }
        }
        
        /// <remarks/>
        public NominaReceptor Receptor {
            get {
                return this.receptorField;
            }
            set {
                this.receptorField = value;
            }
        }
        
        /// <remarks/>
        public NominaPercepciones Percepciones {
            get {
                return this.percepcionesField;
            }
            set {
                this.percepcionesField = value;
            }
        }
        
        /// <remarks/>
        public NominaDeducciones Deducciones {
            get {
                return this.deduccionesField;
            }
            set {
                this.deduccionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OtroPago", IsNullable=false)]
        public NominaOtroPago[] OtrosPagos {
            get {
                return this.otrosPagosField;
            }
            set {
                this.otrosPagosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Incapacidad", IsNullable=false)]
        public NominaIncapacidad[] Incapacidades {
            get {
                return this.incapacidadesField;
            }
            set {
                this.incapacidadesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_TipoNomina TipoNomina {
            get {
                return this.tipoNominaField;
            }
            set {
                this.tipoNominaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime FechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime FechaInicialPago {
            get {
                return this.fechaInicialPagoField;
            }
            set {
                this.fechaInicialPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime FechaFinalPago {
            get {
                return this.fechaFinalPagoField;
            }
            set {
                this.fechaFinalPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal NumDiasPagados {
            get {
                return this.numDiasPagadosField;
            }
            set {
                this.numDiasPagadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalPercepciones {
            get {
                return this.totalPercepcionesField;
            }
            set {
                this.totalPercepcionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalPercepcionesSpecified {
            get {
                return this.totalPercepcionesFieldSpecified;
            }
            set {
                this.totalPercepcionesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDeducciones {
            get {
                return this.totalDeduccionesField;
            }
            set {
                this.totalDeduccionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalDeduccionesSpecified {
            get {
                return this.totalDeduccionesFieldSpecified;
            }
            set {
                this.totalDeduccionesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalOtrosPagos {
            get {
                return this.totalOtrosPagosField;
            }
            set {
                this.totalOtrosPagosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalOtrosPagosSpecified {
            get {
                return this.totalOtrosPagosFieldSpecified;
            }
            set {
                this.totalOtrosPagosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaEmisor {
        
        private NominaEmisorEntidadSNCF entidadSNCFField;
        
        private string curpField;
        
        private string registroPatronalField;
        
        private string rfcPatronOrigenField;
        
        /// <remarks/>
        public NominaEmisorEntidadSNCF EntidadSNCF {
            get {
                return this.entidadSNCFField;
            }
            set {
                this.entidadSNCFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Curp {
            get {
                return this.curpField;
            }
            set {
                this.curpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegistroPatronal {
            get {
                return this.registroPatronalField;
            }
            set {
                this.registroPatronalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RfcPatronOrigen {
            get {
                return this.rfcPatronOrigenField;
            }
            set {
                this.rfcPatronOrigenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaEmisorEntidadSNCF {
        
        private c_OrigenRecurso origenRecursoField;
        
        private decimal montoRecursoPropioField;
        
        private bool montoRecursoPropioFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_OrigenRecurso OrigenRecurso {
            get {
                return this.origenRecursoField;
            }
            set {
                this.origenRecursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MontoRecursoPropio {
            get {
                return this.montoRecursoPropioField;
            }
            set {
                this.montoRecursoPropioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MontoRecursoPropioSpecified {
            get {
                return this.montoRecursoPropioFieldSpecified;
            }
            set {
                this.montoRecursoPropioFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaReceptor {
        
        private NominaReceptorSubContratacion[] subContratacionField;
        
        private string curpField;
        
        private string numSeguridadSocialField;
        
        private System.DateTime fechaInicioRelLaboralField;
        
        private bool fechaInicioRelLaboralFieldSpecified;
        
        private string antiguedadField;
        
        private c_TipoContrato tipoContratoField;
        
        private NominaReceptorSindicalizado sindicalizadoField;
        
        private bool sindicalizadoFieldSpecified;
        
        private c_TipoJornada tipoJornadaField;
        
        private bool tipoJornadaFieldSpecified;
        
        private c_TipoRegimen tipoRegimenField;
        
        private string numEmpleadoField;
        
        private string departamentoField;
        
        private string puestoField;
        
        private c_RiesgoPuesto riesgoPuestoField;
        
        private bool riesgoPuestoFieldSpecified;
        
        private c_PeriodicidadPago periodicidadPagoField;
        
        private c_Banco bancoField;
        
        private bool bancoFieldSpecified;
        
        private string cuentaBancariaField;
        
        private decimal salarioBaseCotAporField;
        
        private bool salarioBaseCotAporFieldSpecified;
        
        private decimal salarioDiarioIntegradoField;
        
        private bool salarioDiarioIntegradoFieldSpecified;
        
        private c_Estado claveEntFedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubContratacion")]
        public NominaReceptorSubContratacion[] SubContratacion {
            get {
                return this.subContratacionField;
            }
            set {
                this.subContratacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Curp {
            get {
                return this.curpField;
            }
            set {
                this.curpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumSeguridadSocial {
            get {
                return this.numSeguridadSocialField;
            }
            set {
                this.numSeguridadSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime FechaInicioRelLaboral {
            get {
                return this.fechaInicioRelLaboralField;
            }
            set {
                this.fechaInicioRelLaboralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaInicioRelLaboralSpecified {
            get {
                return this.fechaInicioRelLaboralFieldSpecified;
            }
            set {
                this.fechaInicioRelLaboralFieldSpecified = value;
            }
        }
        
        /// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute("Antigüedad")]
        public string Antiguedad {
            get {
                return this.antiguedadField;
            }
            set {
                this.antiguedadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_TipoContrato TipoContrato {
            get {
                return this.tipoContratoField;
            }
            set {
                this.tipoContratoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public NominaReceptorSindicalizado Sindicalizado {
            get {
                return this.sindicalizadoField;
            }
            set {
                this.sindicalizadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SindicalizadoSpecified {
            get {
                return this.sindicalizadoFieldSpecified;
            }
            set {
                this.sindicalizadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_TipoJornada TipoJornada {
            get {
                return this.tipoJornadaField;
            }
            set {
                this.tipoJornadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoJornadaSpecified {
            get {
                return this.tipoJornadaFieldSpecified;
            }
            set {
                this.tipoJornadaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_TipoRegimen TipoRegimen {
            get {
                return this.tipoRegimenField;
            }
            set {
                this.tipoRegimenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumEmpleado {
            get {
                return this.numEmpleadoField;
            }
            set {
                this.numEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Puesto {
            get {
                return this.puestoField;
            }
            set {
                this.puestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_RiesgoPuesto RiesgoPuesto {
            get {
                return this.riesgoPuestoField;
            }
            set {
                this.riesgoPuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RiesgoPuestoSpecified {
            get {
                return this.riesgoPuestoFieldSpecified;
            }
            set {
                this.riesgoPuestoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_PeriodicidadPago PeriodicidadPago {
            get {
                return this.periodicidadPagoField;
            }
            set {
                this.periodicidadPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_Banco Banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BancoSpecified {
            get {
                return this.bancoFieldSpecified;
            }
            set {
                this.bancoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CuentaBancaria {
            get {
                return this.cuentaBancariaField;
            }
            set {
                this.cuentaBancariaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SalarioBaseCotApor {
            get {
                return this.salarioBaseCotAporField;
            }
            set {
                this.salarioBaseCotAporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalarioBaseCotAporSpecified {
            get {
                return this.salarioBaseCotAporFieldSpecified;
            }
            set {
                this.salarioBaseCotAporFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SalarioDiarioIntegrado {
            get {
                return this.salarioDiarioIntegradoField;
            }
            set {
                this.salarioDiarioIntegradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalarioDiarioIntegradoSpecified {
            get {
                return this.salarioDiarioIntegradoFieldSpecified;
            }
            set {
                this.salarioDiarioIntegradoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_Estado ClaveEntFed {
            get {
                return this.claveEntFedField;
            }
            set {
                this.claveEntFedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaReceptorSubContratacion {
        
        private string rfcLaboraField;
        
        private decimal porcentajeTiempoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RfcLabora {
            get {
                return this.rfcLaboraField;
            }
            set {
                this.rfcLaboraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PorcentajeTiempo {
            get {
                return this.porcentajeTiempoField;
            }
            set {
                this.porcentajeTiempoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaPercepciones {
        
        private NominaPercepcionesPercepcion[] percepcionField;
        
        private NominaPercepcionesJubilacionPensionRetiro jubilacionPensionRetiroField;
        
        private NominaPercepcionesSeparacionIndemnizacion separacionIndemnizacionField;
        
        private decimal totalSueldosField;
        
        private bool totalSueldosFieldSpecified;
        
        private decimal totalSeparacionIndemnizacionField;
        
        private bool totalSeparacionIndemnizacionFieldSpecified;
        
        private decimal totalJubilacionPensionRetiroField;
        
        private bool totalJubilacionPensionRetiroFieldSpecified;
        
        private decimal totalGravadoField;
        
        private decimal totalExentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Percepcion")]
        public NominaPercepcionesPercepcion[] Percepcion {
            get {
                return this.percepcionField;
            }
            set {
                this.percepcionField = value;
            }
        }
        
        /// <remarks/>
        public NominaPercepcionesJubilacionPensionRetiro JubilacionPensionRetiro {
            get {
                return this.jubilacionPensionRetiroField;
            }
            set {
                this.jubilacionPensionRetiroField = value;
            }
        }
        
        /// <remarks/>
        public NominaPercepcionesSeparacionIndemnizacion SeparacionIndemnizacion {
            get {
                return this.separacionIndemnizacionField;
            }
            set {
                this.separacionIndemnizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalSueldos {
            get {
                return this.totalSueldosField;
            }
            set {
                this.totalSueldosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSueldosSpecified {
            get {
                return this.totalSueldosFieldSpecified;
            }
            set {
                this.totalSueldosFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalSeparacionIndemnizacion {
            get {
                return this.totalSeparacionIndemnizacionField;
            }
            set {
                this.totalSeparacionIndemnizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSeparacionIndemnizacionSpecified {
            get {
                return this.totalSeparacionIndemnizacionFieldSpecified;
            }
            set {
                this.totalSeparacionIndemnizacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalJubilacionPensionRetiro {
            get {
                return this.totalJubilacionPensionRetiroField;
            }
            set {
                this.totalJubilacionPensionRetiroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalJubilacionPensionRetiroSpecified {
            get {
                return this.totalJubilacionPensionRetiroFieldSpecified;
            }
            set {
                this.totalJubilacionPensionRetiroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalGravado {
            get {
                return this.totalGravadoField;
            }
            set {
                this.totalGravadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalExento {
            get {
                return this.totalExentoField;
            }
            set {
                this.totalExentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaPercepcionesPercepcion {
        
        private NominaPercepcionesPercepcionAccionesOTitulos accionesOTitulosField;
        
        private NominaPercepcionesPercepcionHorasExtra[] horasExtraField;
        
        private c_TipoPercepcion tipoPercepcionField;
        
        private string claveField;
        
        private string conceptoField;
        
        private decimal importeGravadoField;
        
        private decimal importeExentoField;
        
        /// <remarks/>
        public NominaPercepcionesPercepcionAccionesOTitulos AccionesOTitulos {
            get {
                return this.accionesOTitulosField;
            }
            set {
                this.accionesOTitulosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HorasExtra")]
        public NominaPercepcionesPercepcionHorasExtra[] HorasExtra {
            get {
                return this.horasExtraField;
            }
            set {
                this.horasExtraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_TipoPercepcion TipoPercepcion {
            get {
                return this.tipoPercepcionField;
            }
            set {
                this.tipoPercepcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ImporteGravado {
            get {
                return this.importeGravadoField;
            }
            set {
                this.importeGravadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ImporteExento {
            get {
                return this.importeExentoField;
            }
            set {
                this.importeExentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaPercepcionesPercepcionAccionesOTitulos {
        
        private decimal valorMercadoField;
        
        private decimal precioAlOtorgarseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ValorMercado {
            get {
                return this.valorMercadoField;
            }
            set {
                this.valorMercadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PrecioAlOtorgarse {
            get {
                return this.precioAlOtorgarseField;
            }
            set {
                this.precioAlOtorgarseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaPercepcionesPercepcionHorasExtra {
        
        private int diasField;
        
        private c_TipoHoras tipoHorasField;
        
        private int horasExtraField;
        
        private decimal importePagadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Dias {
            get {
                return this.diasField;
            }
            set {
                this.diasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_TipoHoras TipoHoras {
            get {
                return this.tipoHorasField;
            }
            set {
                this.tipoHorasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int HorasExtra {
            get {
                return this.horasExtraField;
            }
            set {
                this.horasExtraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ImportePagado {
            get {
                return this.importePagadoField;
            }
            set {
                this.importePagadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaPercepcionesJubilacionPensionRetiro {
        
        private decimal totalUnaExhibicionField;
        
        private bool totalUnaExhibicionFieldSpecified;
        
        private decimal totalParcialidadField;
        
        private bool totalParcialidadFieldSpecified;
        
        private decimal montoDiarioField;
        
        private bool montoDiarioFieldSpecified;
        
        private decimal ingresoAcumulableField;
        
        private decimal ingresoNoAcumulableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalUnaExhibicion {
            get {
                return this.totalUnaExhibicionField;
            }
            set {
                this.totalUnaExhibicionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalUnaExhibicionSpecified {
            get {
                return this.totalUnaExhibicionFieldSpecified;
            }
            set {
                this.totalUnaExhibicionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalParcialidad {
            get {
                return this.totalParcialidadField;
            }
            set {
                this.totalParcialidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalParcialidadSpecified {
            get {
                return this.totalParcialidadFieldSpecified;
            }
            set {
                this.totalParcialidadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MontoDiario {
            get {
                return this.montoDiarioField;
            }
            set {
                this.montoDiarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MontoDiarioSpecified {
            get {
                return this.montoDiarioFieldSpecified;
            }
            set {
                this.montoDiarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal IngresoAcumulable {
            get {
                return this.ingresoAcumulableField;
            }
            set {
                this.ingresoAcumulableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal IngresoNoAcumulable {
            get {
                return this.ingresoNoAcumulableField;
            }
            set {
                this.ingresoNoAcumulableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaPercepcionesSeparacionIndemnizacion {
        
        private decimal totalPagadoField;
        
        private int numAnosServicioField;
        
        private decimal ultimoSueldoMensOrdField;
        
        private decimal ingresoAcumulableField;
        
        private decimal ingresoNoAcumulableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalPagado {
            get {
                return this.totalPagadoField;
            }
            set {
                this.totalPagadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("NumAñosServicio")]
        public int NumAnosServicio {
            get {
                return this.numAnosServicioField;
            }
            set {
                this.numAnosServicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal UltimoSueldoMensOrd {
            get {
                return this.ultimoSueldoMensOrdField;
            }
            set {
                this.ultimoSueldoMensOrdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal IngresoAcumulable {
            get {
                return this.ingresoAcumulableField;
            }
            set {
                this.ingresoAcumulableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal IngresoNoAcumulable {
            get {
                return this.ingresoNoAcumulableField;
            }
            set {
                this.ingresoNoAcumulableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaDeducciones {
        
        private NominaDeduccionesDeduccion[] deduccionField;
        
        private decimal totalOtrasDeduccionesField;
        
        private bool totalOtrasDeduccionesFieldSpecified;
        
        private decimal totalImpuestosRetenidosField;
        
        private bool totalImpuestosRetenidosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Deduccion")]
        public NominaDeduccionesDeduccion[] Deduccion {
            get {
                return this.deduccionField;
            }
            set {
                this.deduccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalOtrasDeducciones {
            get {
                return this.totalOtrasDeduccionesField;
            }
            set {
                this.totalOtrasDeduccionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalOtrasDeduccionesSpecified {
            get {
                return this.totalOtrasDeduccionesFieldSpecified;
            }
            set {
                this.totalOtrasDeduccionesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalImpuestosRetenidos {
            get {
                return this.totalImpuestosRetenidosField;
            }
            set {
                this.totalImpuestosRetenidosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalImpuestosRetenidosSpecified {
            get {
                return this.totalImpuestosRetenidosFieldSpecified;
            }
            set {
                this.totalImpuestosRetenidosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaDeduccionesDeduccion {
        
        private c_TipoDeduccion tipoDeduccionField;
        
        private string claveField;
        
        private string conceptoField;
        
        private decimal importeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_TipoDeduccion TipoDeduccion {
            get {
                return this.tipoDeduccionField;
            }
            set {
                this.tipoDeduccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaOtroPago {
        
        private NominaOtroPagoSubsidioAlEmpleo subsidioAlEmpleoField;
        
        private NominaOtroPagoCompensacionSaldosAFavor compensacionSaldosAFavorField;
        
        private c_TipoOtroPago tipoOtroPagoField;
        
        private string claveField;
        
        private string conceptoField;
        
        private decimal importeField;
        
        /// <remarks/>
        public NominaOtroPagoSubsidioAlEmpleo SubsidioAlEmpleo {
            get {
                return this.subsidioAlEmpleoField;
            }
            set {
                this.subsidioAlEmpleoField = value;
            }
        }
        
        /// <remarks/>
        public NominaOtroPagoCompensacionSaldosAFavor CompensacionSaldosAFavor {
            get {
                return this.compensacionSaldosAFavorField;
            }
            set {
                this.compensacionSaldosAFavorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_TipoOtroPago TipoOtroPago {
            get {
                return this.tipoOtroPagoField;
            }
            set {
                this.tipoOtroPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaOtroPagoSubsidioAlEmpleo {
        
        private decimal subsidioCausadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SubsidioCausado {
            get {
                return this.subsidioCausadoField;
            }
            set {
                this.subsidioCausadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaOtroPagoCompensacionSaldosAFavor {
        
        private decimal saldoAFavorField;
        
        private short anoField;
        
        private decimal remanenteSalFavField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SaldoAFavor {
            get {
                return this.saldoAFavorField;
            }
            set {
                this.saldoAFavorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Año")]
        public short Ano {
            get {
                return this.anoField;
            }
            set {
                this.anoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal RemanenteSalFav {
            get {
                return this.remanenteSalFavField;
            }
            set {
                this.remanenteSalFavField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/nomina12")]
    public partial class NominaIncapacidad {
        
        private int diasIncapacidadField;
        
        private c_TipoIncapacidad tipoIncapacidadField;
        
        private decimal importeMonetarioField;
        
        private bool importeMonetarioFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DiasIncapacidad {
            get {
                return this.diasIncapacidadField;
            }
            set {
                this.diasIncapacidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_TipoIncapacidad TipoIncapacidad {
            get {
                return this.tipoIncapacidadField;
            }
            set {
                this.tipoIncapacidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ImporteMonetario {
            get {
                return this.importeMonetarioField;
            }
            set {
                this.importeMonetarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImporteMonetarioSpecified {
            get {
                return this.importeMonetarioFieldSpecified;
            }
            set {
                this.importeMonetarioFieldSpecified = value;
            }
        }
    }
}