//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8789
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace Mictlanix.CFDv33 {
	using System.Xml.Serialization;


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/Pagos")]
	[System.Xml.Serialization.XmlRootAttribute (Namespace = "http://www.sat.gob.mx/Pagos", IsNullable = false)]
	public partial class Pagos {

		private PagosPago [] pagoField;

		private string versionField;

		public Pagos ()
		{
			this.versionField = "1.0";
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute ("Pago")]
		public PagosPago [] Pago {
			get {
				return this.pagoField;
			}
			set {
				this.pagoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Version {
			get {
				return this.versionField;
			}
			set {
				this.versionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/Pagos")]
	public partial class PagosPago {

		private PagosPagoDoctoRelacionado [] doctoRelacionadoField;

		private PagosPagoImpuestos [] impuestosField;

		private System.DateTime fechaPagoField;

		private c_FormaPago formaDePagoPField;

		private string monedaPField;

		private decimal tipoCambioPField;

		private bool tipoCambioPFieldSpecified;

		private decimal montoField;

		private string numOperacionField;

		private string rfcEmisorCtaOrdField;

		private string nomBancoOrdExtField;

		private string ctaOrdenanteField;

		private string rfcEmisorCtaBenField;

		private string ctaBeneficiarioField;

		private c_TipoCadenaPago tipoCadPagoField;

		private bool tipoCadPagoFieldSpecified;

		private byte [] certPagoField;

		private string cadPagoField;

		private byte [] selloPagoField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute ("DoctoRelacionado")]
		public PagosPagoDoctoRelacionado [] DoctoRelacionado {
			get {
				return this.doctoRelacionadoField;
			}
			set {
				this.doctoRelacionadoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute ("Impuestos")]
		public PagosPagoImpuestos [] Impuestos {
			get {
				return this.impuestosField;
			}
			set {
				this.impuestosField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public System.DateTime FechaPago {
			get {
				return this.fechaPagoField;
			}
			set {
				this.fechaPagoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public c_FormaPago FormaDePagoP {
			get {
				return this.formaDePagoPField;
			}
			set {
				this.formaDePagoPField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string MonedaP {
			get {
				return this.monedaPField;
			}
			set {
				this.monedaPField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal TipoCambioP {
			get {
				return this.tipoCambioPField;
			}
			set {
				this.tipoCambioPField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool TipoCambioPSpecified {
			get {
				return this.tipoCambioPFieldSpecified;
			}
			set {
				this.tipoCambioPFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal Monto {
			get {
				return this.montoField;
			}
			set {
				this.montoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NumOperacion {
			get {
				return this.numOperacionField;
			}
			set {
				this.numOperacionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string RfcEmisorCtaOrd {
			get {
				return this.rfcEmisorCtaOrdField;
			}
			set {
				this.rfcEmisorCtaOrdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string NomBancoOrdExt {
			get {
				return this.nomBancoOrdExtField;
			}
			set {
				this.nomBancoOrdExtField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string CtaOrdenante {
			get {
				return this.ctaOrdenanteField;
			}
			set {
				this.ctaOrdenanteField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string RfcEmisorCtaBen {
			get {
				return this.rfcEmisorCtaBenField;
			}
			set {
				this.rfcEmisorCtaBenField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string CtaBeneficiario {
			get {
				return this.ctaBeneficiarioField;
			}
			set {
				this.ctaBeneficiarioField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public c_TipoCadenaPago TipoCadPago {
			get {
				return this.tipoCadPagoField;
			}
			set {
				this.tipoCadPagoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool TipoCadPagoSpecified {
			get {
				return this.tipoCadPagoFieldSpecified;
			}
			set {
				this.tipoCadPagoFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute (DataType = "base64Binary")]
		public byte [] CertPago {
			get {
				return this.certPagoField;
			}
			set {
				this.certPagoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string CadPago {
			get {
				return this.cadPagoField;
			}
			set {
				this.cadPagoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute (DataType = "base64Binary")]
		public byte [] SelloPago {
			get {
				return this.selloPagoField;
			}
			set {
				this.selloPagoField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/Pagos")]
	public partial class PagosPagoDoctoRelacionado {

		private string idDocumentoField;

		private string serieField;

		private string folioField;

		private string monedaDRField;

		private decimal tipoCambioDRField;

		private bool tipoCambioDRFieldSpecified;

		private c_MetodoPago metodoDePagoDRField;

		private string numParcialidadField;

		private decimal impSaldoAntField;

		private bool impSaldoAntFieldSpecified;

		private decimal impPagadoField;

		private bool impPagadoFieldSpecified;

		private decimal impSaldoInsolutoField;

		private bool impSaldoInsolutoFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string IdDocumento {
			get {
				return this.idDocumentoField;
			}
			set {
				this.idDocumentoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Serie {
			get {
				return this.serieField;
			}
			set {
				this.serieField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string Folio {
			get {
				return this.folioField;
			}
			set {
				this.folioField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public string MonedaDR {
			get {
				return this.monedaDRField;
			}
			set {
				this.monedaDRField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal TipoCambioDR {
			get {
				return this.tipoCambioDRField;
			}
			set {
				this.tipoCambioDRField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool TipoCambioDRSpecified {
			get {
				return this.tipoCambioDRFieldSpecified;
			}
			set {
				this.tipoCambioDRFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public c_MetodoPago MetodoDePagoDR {
			get {
				return this.metodoDePagoDRField;
			}
			set {
				this.metodoDePagoDRField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute (DataType = "integer")]
		public string NumParcialidad {
			get {
				return this.numParcialidadField;
			}
			set {
				this.numParcialidadField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal ImpSaldoAnt {
			get {
				return this.impSaldoAntField;
			}
			set {
				this.impSaldoAntField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool ImpSaldoAntSpecified {
			get {
				return this.impSaldoAntFieldSpecified;
			}
			set {
				this.impSaldoAntFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal ImpPagado {
			get {
				return this.impPagadoField;
			}
			set {
				this.impPagadoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool ImpPagadoSpecified {
			get {
				return this.impPagadoFieldSpecified;
			}
			set {
				this.impPagadoFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal ImpSaldoInsoluto {
			get {
				return this.impSaldoInsolutoField;
			}
			set {
				this.impSaldoInsolutoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool ImpSaldoInsolutoSpecified {
			get {
				return this.impSaldoInsolutoFieldSpecified;
			}
			set {
				this.impSaldoInsolutoFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/Pagos")]
	public partial class PagosPagoImpuestos {

		private PagosPagoImpuestosRetencion [] retencionesField;

		private PagosPagoImpuestosTraslado [] trasladosField;

		private decimal totalImpuestosRetenidosField;

		private bool totalImpuestosRetenidosFieldSpecified;

		private decimal totalImpuestosTrasladadosField;

		private bool totalImpuestosTrasladadosFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute ("Retencion", IsNullable = false)]
		public PagosPagoImpuestosRetencion [] Retenciones {
			get {
				return this.retencionesField;
			}
			set {
				this.retencionesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute ("Traslado", IsNullable = false)]
		public PagosPagoImpuestosTraslado [] Traslados {
			get {
				return this.trasladosField;
			}
			set {
				this.trasladosField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal TotalImpuestosRetenidos {
			get {
				return this.totalImpuestosRetenidosField;
			}
			set {
				this.totalImpuestosRetenidosField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool TotalImpuestosRetenidosSpecified {
			get {
				return this.totalImpuestosRetenidosFieldSpecified;
			}
			set {
				this.totalImpuestosRetenidosFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal TotalImpuestosTrasladados {
			get {
				return this.totalImpuestosTrasladadosField;
			}
			set {
				this.totalImpuestosTrasladadosField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute ()]
		public bool TotalImpuestosTrasladadosSpecified {
			get {
				return this.totalImpuestosTrasladadosFieldSpecified;
			}
			set {
				this.totalImpuestosTrasladadosFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/Pagos")]
	public partial class PagosPagoImpuestosRetencion {

		private c_Impuesto impuestoField;

		private decimal importeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public c_Impuesto Impuesto {
			get {
				return this.impuestoField;
			}
			set {
				this.impuestoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal Importe {
			get {
				return this.importeField;
			}
			set {
				this.importeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute ()]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "http://www.sat.gob.mx/Pagos")]
	public partial class PagosPagoImpuestosTraslado {

		private c_Impuesto impuestoField;

		private c_TipoFactor tipoFactorField;

		private decimal tasaOCuotaField;

		private decimal importeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public c_Impuesto Impuesto {
			get {
				return this.impuestoField;
			}
			set {
				this.impuestoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public c_TipoFactor TipoFactor {
			get {
				return this.tipoFactorField;
			}
			set {
				this.tipoFactorField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal TasaOCuota {
			get {
				return this.tasaOCuotaField;
			}
			set {
				this.tasaOCuotaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute ()]
		public decimal Importe {
			get {
				return this.importeField;
			}
			set {
				this.importeField = value;
			}
		}
	}
}